on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
      branches:
        - '**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: 8.0
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
            coverage: none
            tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress

      - name: Setup env
        run: cp .env.example .env && php artisan key:generate

      - name: Execute PHP Tests
        run: vendor/bin/phpunit

      - name: Install JS dependencies
        run: npm ci

      - name: Build assets
        run: npm run build
